type Query {
    nodeById(id: ID): Node
    edgeById(id: ID): Edge
    projectById(id: ID): Project
    projectMemberById(id: ID): ProjectMember
    projectMembershipsByUserId(userId: ID!): [ProjectMember]
    projectMembershipsByProjectId(projectId: ID!): [ProjectMember]
    projectMembershipsByUserIdAndProjectRole(userId: ID!, projectRole: ProjectRole!): [ProjectMember]
    userRoleInProject(userId: ID!, projectId: ID!): ProjectRole
    userById(id: ID): User
    allNodes: [Node]
    allEdges: [Edge]
    allProjects: [Project]
    allUsers: [User]
}

type Mutation {
    createNode(newNodeData: NodeInput!): Node
    createEdge(newEdgeData: EdgeInput!): Edge
    updateProject(id: ID!, updatedProjectData: ProjectInput): Project
}

input NodeInput {
    name: String!
    type: NodeType
    xPos: Float
    yPos: Float
    projectId: ID
}

input EdgeInput {
    sourceNodeId: ID!
    targetNodeId: ID!
    projectId: ID
}

input ProjectInput {
    name: String
    description: String
    createdById: ID
    isPublic: Boolean
    nodeIds: [ID]
    edgeIds: [ID]
    memberIds: [ID]
}

enum NodeType {
    DATABASE
    GATEWAY
    QUEUE
    SERVICE
}

type Node {
    id: ID!
    name: String
    type: NodeType
    xPos: Float
    yPos: Float
    project: Project!
}

type Edge {
    id: ID!
    sourceNode: Node
    targetNode: Node
    project: Project!
}

type Project {
    id: ID!
    name: String
    description: String
    nodes: [Node]
    edges: [Edge]
    members: [ProjectMember]
    createdBy: User
    createdAt: String
    updatedAt: String
    isPublic: Boolean

}

enum UserRole {
    ADMIN
    USER
}

type User {
    id: ID!
    username: String
    email: String
    role: UserRole
    projectMemberships: [ProjectMember]
}

type ProjectMember {
    id: ID!
    user: User
    project: Project
    projectRole: ProjectRole
    joinedAt: String
}

enum ProjectRole {
    OWNER
    EDITOR
    VIEWER
}