blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/systructure/systructure/discussions
    about: Ask questions or start a discussion instead of opening an issue
